### ISSUE TITLE
edit_graph function

### ISSUE THREAD

**Issue by supersoob** [parasj/checkmate#150]
Hi, I tried to run ResNet101 as described in the tutorial.
However, the epoch time (training whole dataset) is too short while I run the model with checkmate.
I thought it takes longer time than standard training time because of recomputation time but it's almost same. So I checked out the code and doubted that the sched_result is not updated to new graph in edit_graph function of checkmate/tf2/execution.py. Can you check it? Thank you.

`def edit_graph(fxn, op_dict, schedule: Schedule):
    registers = dict()
    output_ops = set(t.op for t in fxn.outputs)
    duplicate_ops = []
    sched_ordered = list(enumerate([s for s in schedule if isinstance(s, OperatorEvaluation)]))
    # duplicate rematerialized operation
    for i, inst in sched_ordered:
        op = op_dict[inst.id]
        new_op = op if op in output_ops else copy_op(op, "{}_copy_at_sched_idx{}".format(op.name, i))
        duplicate_ops.append(new_op)

    # match up args, and assign outputs
    for i, inst in sched_ordered:
        args = [arg for i in inst.arg_regs for arg in registers[i]]
        new_op = duplicate_ops[i]
        for arg in args:
            for j, inp in enumerate(new_op.inputs):
                if can_replace(inp, arg):
                    new_op._update_input(j, arg)
        registers[inst.out_register] = new_op.outputs

    # I think the registers list does not affect fxn (graph) at all
    return fxn'

**Comment by aninrusimha** [comment]
Sorry for the delay, I'm trying to replicate.  Did you try to edit a graph for a model directly or did you use compile_tf2 to generate gradients?

**Comment by supersoob** [comment]
I didn't try modify anything in given code. I just followed tutorial/tutorial_basic_tf2_example.ipynb (which runs compile_tf2(...) in the code). And then I measured the iteration time and memory usage, but the time and memory usage using gurobi_solver was almost same with the normal training.

**Comment by closest-git** [comment]
It's really strange why edit_graph would return unmodified fnx. And why the author would publish such non-working function?
Anyway, ILP is too slow for the rematerialization problem.

**Comment by parasj** [comment]
@closest-git Yingshi, I'm sorry you feel that way. If you're still having issues with the codebase, please email me (address in profile). This is a research codebase, so not all bugs have been ironed out. We've released it in order to promote reproducibility as well as hopefully assist people extending our work as a baseline in future publications and projects.

We ran the experiments using manually modified graphs based on the results of our rematerialization algorithm. For a higher-performance implementation of rematerialization, see the `mlsys20_artifact` branch. Happy to answer other questions over email as well.
